### ISSUE TITLE
Pipeline log cuts offs the end

### ISSUE THREAD

**Issue by cyberbikepunk** [frictionlessdata/datapackage-pipelines#16]
@akariv please check out the [Malta log](http://staging.openspending.org/pipelines/#anchor-eu-structural-funds-data-mt-malta-mt-malta). I would expect it to cut the beginning off if too long.

**Comment by akariv** [comment]
It's not cut - the `sniff_and_cast` processor fails with this exception:
```
/usr/lib/python3.5/site-packages/jsontableschema/model.py:48: UserWarning: Class models.SchemaModel is deprecated [v0.7-v1)
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/remote/eu-structural-funds/common/processors/sniff_and_cast.py", line 290, in <module>
    casters_ = get_casters(datapackage_, resource_sample_)
  File "/remote/eu-structural-funds/common/processors/sniff_and_cast.py", line 233, in get_casters
    caster = sniffer.get_caster()
  File "/remote/eu-structural-funds/common/processors/sniff_and_cast.py", line 100, in get_caster
    return self._guess_caster()
  File "/remote/eu-structural-funds/common/processors/sniff_and_cast.py", line 128, in _guess_caster
    assert self._pre_cast_checks_ok(raw_value)
  File "/remote/eu-structural-funds/common/processors/sniff_and_cast.py", line 175, in _pre_cast_checks_ok
    if value.count(self.format['decimalChar']) > 1:
AttributeError: 'float' object has no attribute 'count'
```

Then all other processors in the pipelines are forcefully killed - so their output might be cut in the middle.
