### ISSUE TITLE
Sample pipeline on Windows 10

### ISSUE THREAD

**Issue by jheeffer** [frictionlessdata/datapackage-pipelines#51]
Hey Adam!

Is Windows supported for the datapackage-pipelines package?
I got it to work on bash on windows, but windows native I get the following error:

```
C:\dpp\wb_test>dpp run all
INFO    :Main                            :Skipping redis connection, host:None, port:6379
DEBUG   :Main                            :Using selector: SelectSelector
INFO    :Main                            :RUNNING .\worldbank-co2-emissions
INFO    :Main                            :- add_metadata
Traceback (most recent call last):
  File "C:\Users\Jasper Heeffer\AppData\Local\Programs\Python\Python36-32\Scripts\dpp-script.py", line 11, in <module>
    load_entry_point('datapackage-pipelines==1.0.14', 'console_scripts', 'dpp')()
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\datapackage_pipelines\cli.py", line 68, in run
    execute_if_needed(pipeline_id, spec, use_cache)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\datapackage_pipelines\cli.py", line 40, in execute_if_needed
    use_cache=use_cache)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\datapackage_pipelines\manager\tasks.py", line 254, in execute_pipeline
    return loop.run_until_complete(pipeline_task)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\datapackage_pipelines\manager\tasks.py", line 187, in async_execute_pipeline
    await construct_process_pipeline(pipeline_steps, pipeline_cwd, errors)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\datapackage_pipelines\manager\tasks.py", line 135, in construct_process_pipeline
    process = await create_process(args, pipeline_cwd, wfd, rfd)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\asyncio\subprocess.py", line 225, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\asyncio\base_events.py", line 1190, in subprocess_exec
    bufsize, **kwargs)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\asyncio\coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\asyncio\base_events.py", line 340, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
ERROR   :Main                            :Task was destroyed but it is pending!
task: <Task pending coro=<dequeue_errors() running at c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\datapackage_pipelines\manager\tasks.py:29> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x04766A50>()]>>
Exception ignored in: <coroutine object dequeue_errors at 0x04767B40>
Traceback (most recent call last):
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\site-packages\datapackage_pipelines\manager\tasks.py", line 29, in dequeue_errors
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\asyncio\queues.py", line 169, in get
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\asyncio\base_events.py", line 573, in call_soon
  File "c:\users\jasper heeffer\appdata\local\programs\python\python36-32\lib\asyncio\base_events.py", line 357, in _check_closed
RuntimeError: Event loop is closed
```

* Python 3.6
* Windows 10

**Comment by akariv** [comment]
I think this is a problem related to the fact that `asyncio` is not well supported on Windows: https://docs.python.org/3/library/asyncio-eventloops.html#windows

Adding support for Windows means changing a very basic aspect of how this library works (i.e. communication via pipes), so I don't think it will happen any time soon.
