### ISSUE TITLE
Error creating valid datetime fields in Data Packages

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/datapackage-pipelines#60]
```
enliten:
  pipeline:
    - run: add_metadata
      parameters:
        name: 'enliten'
        title: 'ENLITEN'
        homepage: 'http://www.cs.bath.ac.uk/enliten/'
        temporal:
          name: 'Data Collected'
          start: '2013-10-01'
          end: '2015-06-30'
    - parameters:
        name: humidity
        table: humidity
        url: mysql://root@localhost/enliten
      run: add_resource
    - run: stream_remote_resources
    - run: set_types
      parameters:
        resources: humidity
        types:
          '_id':
            type: integer
          device:
            type: integer
          sensor:
            type: integer
          humidity:
            type: number
          timestamp:
            type: datetime
    - run: dump.to_path
      parameters:
        out-path: ../_datasets/enliten
```

produces

```
(pilot-dm4t) legend:pilot-dm4t dan (convert-to-datapackage-pipelines)$ dpp run ./enliten/enliten
INFO    :Main                            :Skipping redis connection, host:None, port:6379
INFO    :Main                            :RUNNING ./enliten/enliten
INFO    :Main                            :- add_metadata
INFO    :Main                            :- add_resource
INFO    :Main                            :- stream_remote_resources
INFO    :Main                            :- set_types
INFO    :Main                            :- dump.to_path
INFO    :Main                            :- (sink)
INFO    :Main                            :DONE /Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/add_metadata.py
INFO    :Main                            :DONE /Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/add_resource.py
INFO    :Main                            :stream_remote_resources: INFO    :enliten: OPENING mysql://root@localhost/enliten
INFO    :Main                            :stream_remote_resources: ERROR   :Exception during reset or similar
INFO    :Main                            :stream_remote_resources: Traceback (most recent call last):
INFO    :Main                            :stream_remote_resources:   File "/Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
INFO    :Main                            :stream_remote_resources:     fairy._reset(pool)
INFO    :Main                            :stream_remote_resources:   File "/Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/sqlalchemy/pool.py", line 829, in _reset
INFO    :Main                            :stream_remote_resources:     pool._dialect.do_rollback(self)
INFO    :Main                            :stream_remote_resources:   File "/Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 1598, in do_rollback
INFO    :Main                            :stream_remote_resources:     dbapi_connection.rollback()
INFO    :Main                            :stream_remote_resources: _mysql_exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
INFO    :Main                            :set_types: /Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/jsontableschema/model.py:48: UserWarning: Class models.SchemaModel is deprecated [v0.7-v1)
INFO    :Main                            :set_types:   warnings.warn(message, UserWarning)
INFO    :Main                            :set_types: ERROR   :Failed to cast row ['1', '1', '4', '33.0', '2013-03-15T00:29:11']
INFO    :Main                            :set_types: Traceback (most recent call last):
INFO    :Main                            :set_types:   File "/Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/jsontableschema/types/datetime.py", line 43, in cast_default
INFO    :Main                            :set_types:     return datetime.datetime.strptime(value, self.ISO8601)
INFO    :Main                            :set_types:   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
INFO    :Main                            :set_types:     tt, fraction = _strptime(data_string, format)
INFO    :Main                            :set_types:   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 362, in _strptime
INFO    :Main                            :set_types:     (data_string, format))
INFO    :Main                            :set_types: ValueError: time data '2013-03-15T00:29:11' does not match format '%Y-%m-%dT%H:%M:%SZ'
INFO    :Main                            :set_types: During handling of the above exception, another exception occurred:
INFO    :Main                            :set_types: Traceback (most recent call last):
INFO    :Main                            :set_types:   File "/Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/set_types.py", line 71, in <module>
INFO    :Main                            :set_types:     spew(datapackage, process_resources(resource_iterator))
INFO    :Main                            :set_types:   File "/Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 59, in spew
INFO    :Main                            :set_types:     for rec in res:
INFO    :Main                            :set_types:   File "/Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/set_types.py", line 52, in process_resource
INFO    :Main                            :set_types:     flattened_row = jts.cast_row(flattened_row)
INFO    :Main                            :set_types:   File "/Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/jsontableschema/schema.py", line 81, in cast_row
INFO    :Main                            :set_types:     result.append(field.cast_value(value))
INFO    :Main                            :set_types:   File "/Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/jsontableschema/field.py", line 76, in cast_value
INFO    :Main                            :set_types:     return self.__type.cast(value, skip_constraints=skip_constraints)
INFO    :Main                            :set_types:   File "/Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/jsontableschema/types/base.py", line 120, in cast
INFO    :Main                            :set_types:     cast_value = cast_func(value, self.__format_fmt)
INFO    :Main                            :set_types:   File "/Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/jsontableschema/types/datetime.py", line 45, in cast_default
INFO    :Main                            :set_types:     raise_with_traceback(exceptions.InvalidDateTimeType(e))
INFO    :Main                            :set_types:   File "/Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
INFO    :Main                            :set_types:     raise exc.with_traceback(traceback)
INFO    :Main                            :set_types:   File "/Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/jsontableschema/types/datetime.py", line 43, in cast_default
INFO    :Main                            :set_types:     return datetime.datetime.strptime(value, self.ISO8601)
INFO    :Main                            :set_types:   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
INFO    :Main                            :set_types:     tt, fraction = _strptime(data_string, format)
INFO    :Main                            :set_types:   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 362, in _strptime
INFO    :Main                            :set_types:     (data_string, format))
INFO    :Main                            :set_types: jsontableschema.exceptions.InvalidDateTimeType: time data '2013-03-15T00:29:11' does not match format '%Y-%m-%dT%H:%M:%SZ'
INFO    :Main                            :stream_remote_resources: ERROR   :Output pipe disappeared!
ERROR   :Main                            :FAILED /Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/set_types.py: 1
ERROR   :Main                            :FAILED /Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/datapackage_pipelines/manager/../lib/internal/sink.py: -9
ERROR   :Main                            :FAILED /Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/stream_remote_resources.py: -9
ERROR   :Main                            :FAILED /Users/dan/open_knowledge/_envs/pilot-dm4t/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/dump/to_path.py: -9
INFO    :Main                            :RESULTS:
INFO    :Main                            :FAILURE: ./enliten/enliten 
```

Adding the `format:` option:

```
            format: 'fmt:%Y-%m-%dT%H:%M:%S'
```

makes it go.  But I end up with an invalid Data Package when trying to read with `datapackage-py`.

```
ValueError: time data '2013-03-15 00:29:11' does not match format '%Y-%m-%dT%H:%M:%SZ'
```

<img width="1103" alt="screen shot 2017-06-06 at 15 05 05" src="https://cloud.githubusercontent.com/assets/772616/26819561/a3eba4c4-4ac9-11e7-8248-598f66d2764c.png">

**Comment by akariv** [comment]
Thanks @danfowler, please update your lib and retry.

**Comment by danfowler** [comment]
Still failing.  I guess because the microseconds (`.%f`) directive doesn't match the date format produced by the pipeline?

```
[2,5] [non-castable-value] Row 2 has non castable value 2013-03-15 00:29:11 in column 5 (type: datetime, format: fmt:%Y-%m-%d %H:%M:%S.%f)
```

**Comment by brew** [comment]
I think I'm having issues with this change too. My [`add_timestamp` processor](https://github.com/okfn/measure/blob/4e5ccd95068d1af11d85519938cd45ece9867384/datapackage_pipelines_measure/processors/add_timestamp.py) has stopped working. I'm not sure adding a 'format' value to the schema makes a difference?

(the `TIMESTAMP_DEFAULT_FORMAT` value is set to `%Y-%m-%dT%H:%M:%SZ`)

```
INFO    :Main                            :dump.to_path: ERROR   :Bad value '2017-07-06T15:27:02Z' for field timestamp
INFO    :Main                            :DONE /Users/brew/virtualenvs/measure/src/measure/datapackage_pipelines_measure/processors/add_timestamp.py
INFO    :Main                            :dump.to_path: Traceback (most recent call last):
INFO    :Main                            :dump.to_path:   File "/Users/brew/virtualenvs/measure/lib/python3.6/site-packages/jsontableschema/types/datetime.py", line 63, in cast_fmt
INFO    :Main                            :dump.to_path:     return datetime.datetime.strptime(value, fmt)
INFO    :Main                            :dump.to_path:   File "/Users/brew/.pyenv/versions/3.6.1/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
INFO    :Main                            :dump.to_path:     tt, fraction = _strptime(data_string, format)
INFO    :Main                            :dump.to_path:   File "/Users/brew/.pyenv/versions/3.6.1/lib/python3.6/_strptime.py", line 362, in _strptime
INFO    :Main                            :dump.to_path:     (data_string, format))
INFO    :Main                            :dump.to_path: ValueError: time data '2017-07-06T15:27:02Z' does not match format '%Y-%m-%d %H:%M:%S.%f'
INFO    :Main                            :dump.to_path: During handling of the above exception, another exception occurred:
INFO    :Main                            :dump.to_path: Traceback (most recent call last):
INFO    :Main                            :dump.to_path:   File "/Users/brew/virtualenvs/measure/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/dump/to_path.py", line 28, in <module>
INFO    :Main                            :dump.to_path:     PathDumper()()
INFO    :Main                            :dump.to_path:   File "/Users/brew/virtualenvs/measure/lib/python3.6/site-packages/datapackage_pipelines/lib/dump/dumper_base.py", line 29, in __call__
INFO    :Main                            :dump.to_path:     self.stats)
INFO    :Main                            :dump.to_path:   File "/Users/brew/virtualenvs/measure/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 59, in spew
INFO    :Main                            :dump.to_path:     for rec in res:
INFO    :Main                            :dump.to_path:   File "/Users/brew/virtualenvs/measure/lib/python3.6/site-packages/datapackage_pipelines/lib/dump/dumper_base.py", line 65, in hasher
INFO    :Main                            :dump.to_path:     for row in resource:
INFO    :Main                            :dump.to_path:   File "/Users/brew/virtualenvs/measure/lib/python3.6/site-packages/datapackage_pipelines/lib/dump/dumper_base.py", line 55, in row_counter
INFO    :Main                            :dump.to_path:     for row in resource:
INFO    :Main                            :dump.to_path:   File "/Users/brew/virtualenvs/measure/lib/python3.6/site-packages/datapackage_pipelines/lib/dump/dumper_base.py", line 164, in rows_processor
INFO    :Main                            :dump.to_path:     for row in resource:
INFO    :Main                            :dump.to_path:   File "/Users/brew/virtualenvs/measure/lib/python3.6/site-packages/datapackage_pipelines/lib/dump/dumper_base.py", line 42, in schema_validator
INFO    :Main                            :dump.to_path:     schema.cast(k, v)
INFO    :Main                            :dump.to_path:   File "/Users/brew/virtualenvs/measure/lib/python3.6/site-packages/jsontableschema/model.py", line 98, in cast
INFO    :Main                            :dump.to_path:     return _type.cast(value)
INFO    :Main                            :dump.to_path:   File "/Users/brew/virtualenvs/measure/lib/python3.6/site-packages/jsontableschema/types/base.py", line 120, in cast
INFO    :Main                            :dump.to_path:     cast_value = cast_func(value, self.__format_fmt)
INFO    :Main                            :dump.to_path:   File "/Users/brew/virtualenvs/measure/lib/python3.6/site-packages/jsontableschema/types/datetime.py", line 65, in cast_fmt
INFO    :Main                            :dump.to_path:     raise_with_traceback(exceptions.InvalidDateTimeType(e))
INFO    :Main                            :dump.to_path:   File "/Users/brew/virtualenvs/measure/lib/python3.6/site-packages/future/utils/__init__.py", line 419, in raise_with_traceback
INFO    :Main                            :dump.to_path:     raise exc.with_traceback(traceback)
INFO    :Main                            :dump.to_path:   File "/Users/brew/virtualenvs/measure/lib/python3.6/site-packages/jsontableschema/types/datetime.py", line 63, in cast_fmt
INFO    :Main                            :dump.to_path:     return datetime.datetime.strptime(value, fmt)
INFO    :Main                            :dump.to_path:   File "/Users/brew/.pyenv/versions/3.6.1/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
INFO    :Main                            :dump.to_path:     tt, fraction = _strptime(data_string, format)
INFO    :Main                            :dump.to_path:   File "/Users/brew/.pyenv/versions/3.6.1/lib/python3.6/_strptime.py", line 362, in _strptime
INFO    :Main                            :dump.to_path:     (data_string, format))
INFO    :Main                            :dump.to_path: jsontableschema.exceptions.InvalidDateTimeType: time data '2017-07-06T15:27:02Z' does not match format '%Y-%m-%d %H:%M:%S.%f'
```

**Comment by akariv** [comment]
When `dpp` writes to CSV, it normalises the formatting - so that the schema and the written data will be in sync (and standard).
With datetime types there was a wrong handling which used the default conversion in Python which is inconsistent (sometimes it has microseconds and sometimes not). 
The above commit is supposed to take care of that.
