### ISSUE TITLE
print() from processors causes error

### ISSUE THREAD

**Issue by brew** [frictionlessdata/datapackage-pipelines#80]
Python 3.6.1 MacOS

I'm writing a pipeline with a very simple processor. If there's a `print()` statement in there, running the pipeline causes this crash:

```
INFO    :Main                            :Skipping redis connection, host:None, port:6379
WARNING :Main                            :No csv processor available for my-first-item
INFO    :Main                            :RUNNING ./my-first-item
INFO    :Main                            :- add_metadata
INFO    :Main                            :- spss.add_spss
INFO    :Main                            :- (sink)
INFO    :Main                            :DONE /Users/brew/virtualenvs/ukds_pilot/lib/python3.6/site-packages/datapackage_pipelines-1.1.8-py3.6.egg/datapackage_pipelines/specs/../lib/add_metadata.py
INFO    :Main                            :(sink): Traceback (most recent call last):
INFO    :Main                            :(sink):   File "/Users/brew/virtualenvs/ukds_pilot/lib/python3.6/site-packages/datapackage_pipelines-1.1.8-py3.6.egg/datapackage_pipelines/manager/../lib/internal/sink.py", line 5, in <module>
INFO    :Main                            :(sink):     params, dp, res_iter = ingest()
INFO    :Main                            :(sink):   File "/Users/brew/virtualenvs/ukds_pilot/lib/python3.6/site-packages/datapackage_pipelines-1.1.8-py3.6.egg/datapackage_pipelines/wrapper/wrapper.py", line 34, in ingest
INFO    :Main                            :(sink):     datapackage, resource_iterator = process_input(sys.stdin, validate, debug)
INFO    :Main                            :(sink):   File "/Users/brew/virtualenvs/ukds_pilot/lib/python3.6/site-packages/datapackage_pipelines-1.1.8-py3.6.egg/datapackage_pipelines/wrapper/input_processor.py", line 63, in process_input
INFO    :Main                            :(sink):     dp = json.loads(dp_json)
INFO    :Main                            :(sink):   File "/Users/brew/virtualenvs/ukds_pilot/lib/python3.6/site-packages/datapackage_pipelines-1.1.8-py3.6.egg/datapackage_pipelines/utilities/extended_json.py", line 123, in _loads
INFO    :Main                            :(sink):     return _json.loads(*args, **kwargs)
INFO    :Main                            :(sink):   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 367, in loads
INFO    :Main                            :(sink):     return cls(**kw).decode(s)
INFO    :Main                            :(sink):   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
INFO    :Main                            :(sink):     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
INFO    :Main                            :(sink):   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
INFO    :Main                            :(sink):     raise JSONDecodeError("Expecting value", s, err.value) from None
INFO    :Main                            :(sink): json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO    :Main                            :DONE /Users/brew/virtualenvs/ukds_pilot/src/datapackage-pipelines-spss/datapackage_pipelines_spss/processors/add_spss.py
ERROR   :Main                            :FAILED /Users/brew/virtualenvs/ukds_pilot/lib/python3.6/site-packages/datapackage_pipelines-1.1.8-py3.6.egg/datapackage_pipelines/manager/../lib/internal/sink.py: 1
WARNING :Main                            :No csv processor available for my-first-item
WARNING :Main                            :No csv processor available for my-first-item
INFO    :Main                            :RESULTS:
INFO    :Main                            :FAILURE: ./my-first-item 
ERROR log from processor (sink):
+--------
| Traceback (most recent call last):
|   File "/Users/brew/virtualenvs/ukds_pilot/lib/python3.6/site-packages/datapackage_pipelines-1.1.8-py3.6.egg/datapackage_pipelines/manager/../lib/internal/sink.py", line 5, in <module>
|     params, dp, res_iter = ingest()
|   File "/Users/brew/virtualenvs/ukds_pilot/lib/python3.6/site-packages/datapackage_pipelines-1.1.8-py3.6.egg/datapackage_pipelines/wrapper/wrapper.py", line 34, in ingest
|     datapackage, resource_iterator = process_input(sys.stdin, validate, debug)
|   File "/Users/brew/virtualenvs/ukds_pilot/lib/python3.6/site-packages/datapackage_pipelines-1.1.8-py3.6.egg/datapackage_pipelines/wrapper/input_processor.py", line 63, in process_input
|     dp = json.loads(dp_json)
|   File "/Users/brew/virtualenvs/ukds_pilot/lib/python3.6/site-packages/datapackage_pipelines-1.1.8-py3.6.egg/datapackage_pipelines/utilities/extended_json.py", line 123, in _loads
|     return _json.loads(*args, **kwargs)
|   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 367, in loads
|     return cls(**kw).decode(s)
|   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
|     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
|   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
|     raise JSONDecodeError("Expecting value", s, err.value) from None
| json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Using the logging module to stout works fine. However, I'm importing third-party modules into the processor that use `print` so can't easily avoid it.

**Comment by vitorbaptista** [comment]
I haven't checked in the code, but my guess is that we can't support `print()` cleanly because we use `stdin`/`stdout` as a communication channel. The `print` is basically adding garbage to the input of the next processor.

The options I see are:
* Change the dependency's code
* Mock `print()`
* https://stackoverflow.com/questions/8391411/suppress-calls-to-print-python (although it'll probably have unwanted side-effects)

**Comment by akariv** [comment]
Thanks @vitorbaptista - that's a very good resource.

**Comment by akariv** [comment]
The primary reason for the standard files is that these are passed to the process on creation.
The alternatives to that would be to create the pipes and `fork()`, which is not supported by python afaik and to use named pipes (which require cleaning after and are a less elegant solution imo).

I'll proceed with the sys.stdout replacement, and I agree with your suggestion of showing the user a warning in case `print` is used instead of silently discarding it.
